application: solid-warehouse
runtime: python27
api_version: 1
threadsafe: true
version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  login: admin

- url: /(.*)
  static_files: static/\1
  upload: static
  login: admin

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/
